In [2]:
import numpy as np

In [2]:
a = [1,2,3]
b = [4,5,6]

In [3]:
np.dot(a,b)

np.int64(32)

In [4]:
a = np.array([[1,2],[3,4]])
a.T


array([[1, 3],
       [2, 4]])

In [2]:
A = np.array([[1,1,3], [1,2,4], [1,1,2]])

In [6]:
B = np.array([[15], [21], [13]])

In [7]:
np.linalg.solve(A, B)

array([[5.],
       [4.],
       [2.]])

In [ ]:
# Matrix multiplication is a function which transform a vector space into another vector space
r = np.array([[2],[4],[5]])
A = np.array([[1,1,3], [1,2,4],[1,1,2]])
np.matmul(A, r)

array([[21],
       [30],
       [16]])

In [4]:
r[0]*A[:,0]+r[1]*A[:,1]+r[2]*A[:,2]

array([21, 30, 16])

In [3]:
A_1 = np.linalg.inv(A)

In [4]:
A_1

array([[ 0., -1.,  2.],
       [-2.,  1.,  1.],
       [ 1., -0., -1.]])

In [5]:
np.matmul(A, A_1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
import cv2
import matplotlib.pyplot as plt
# pip install opencv 

In [ ]:
image = cv2.imread("path of your")
plt.figure()
plt.imshow()
plt.show()

In [ ]:
image.shape

In [3]:
import math
theta = math.radians(30)

rotation_matrix = np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

rotation_matrix

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [ ]:
h, w, c = image.shape
new_np_image = np.zeros(image.shape, dtype="uint8")
new_np_image
plt.figure()
plt.imshow(image, origin='lower')
plt.show()

In [ ]:
# rotation of image
for x in range(w):
    for y in range(h):
        pixel = image[y,x,:]
        new_x, new_y = map(int, np.matmul(rotation_matrix, np.array([[x], [y]])))
        if(0<=new_x<w) and (0<=new_y<h):
            new_np_image[new_y, new_x, :] = pixel

plt.figure()
plt.imshow(new_np_image, origin='lower')



In [ ]:
theta = -30
M = cv2.getRotationMatrix2D((0,0), theta, scaler=1)
new_image = cv2.wrapAffine(image, M, (w,h))
plt.figure()
plt.imshow(new_image, origin='lower')
plt.show()